In [1]:
using Pkg
using DataFrames
using Random

Criando Data Frame

In [2]:
df = DataFrame(A = 1:4, b = ["M", "F", "F", "M"]); df

4×2 DataFrame
│ Row │ A     │ b      │
│     │ Int64 │ String │
├─────┼───────┼────────┤
│ 1   │ 1     │ M      │
│ 2   │ 2     │ F      │
│ 3   │ 3     │ F      │
│ 4   │ 4     │ M      │

Acesaando colunas - 1 Forma

In [3]:
print(df.A)

[1, 2, 3, 4]

Acesaando colunas - 2 Forma

In [4]:
df[!, :A]

4-element Array{Int64,1}:
 1
 2
 3
 4

Acesaando colunas - 2 Forma

In [5]:
df[:, :A]

4-element Array{Int64,1}:
 1
 2
 3
 4

Acessando um valor especifico

In [6]:
df[3, 1]

3

In [7]:
df[1:3, 1]

3-element Array{Int64,1}:
 1
 2
 3

Achando os nomes das colunas


In [8]:
names(df)

2-element Array{Symbol,1}:
 :A
 :b

É possível construir um dataframe

In [9]:
df = DataFrame(); df

0×0 DataFrame

In [10]:
df.A = 1:8
df.B = rand(8)
df.C = ["M", "F", "F", "M", "F", "M", "F", "M"]
df

8×3 DataFrame
│ Row │ A     │ B        │ C      │
│     │ Int64 │ Float64  │ String │
├─────┼───────┼──────────┼────────┤
│ 1   │ 1     │ 0.460526 │ M      │
│ 2   │ 2     │ 0.280326 │ F      │
│ 3   │ 3     │ 0.518959 │ F      │
│ 4   │ 4     │ 0.305763 │ M      │
│ 5   │ 5     │ 0.782518 │ F      │
│ 6   │ 6     │ 0.475982 │ M      │
│ 7   │ 7     │ 0.596618 │ F      │
│ 8   │ 8     │ 0.726469 │ M      │

In [11]:
using LinearAlgebra #Serve para fazer algumas operações com matrizes

Matrizes Especiais

In [12]:
zeros(3, 1)

3×1 Array{Float64,2}:
 0.0
 0.0
 0.0

In [13]:
zeros(3, 3)

3×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [14]:
m1 = ones(4)

4-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0

In [15]:
m2 = ones(4, 2)

4×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0

In [16]:
m3 = zeros(3,1)

3×1 Array{Float64,2}:
 0.0
 0.0
 0.0

In [17]:
id = Matrix(1I, 3, 3) 

3×3 Array{Int64,2}:
 1  0  0
 0  1  0
 0  0  1

Operação com matrizes

In [18]:
m1 = rand(3,3)

3×3 Array{Float64,2}:
 0.796074  0.684539  0.766931
 0.092216  0.751835  0.559261
 0.744266  0.266049  0.928364

In [19]:
2*m1

3×3 Array{Float64,2}:
 1.59215   1.36908   1.53386
 0.184432  1.50367   1.11852
 1.48853   0.532098  1.85673

In [20]:
2m1

3×3 Array{Float64,2}:
 1.59215   1.36908   1.53386
 0.184432  1.50367   1.11852
 1.48853   0.532098  1.85673

In [21]:
2m1 == 2*m1

true

In [22]:
m2 = rand(3,3)

3×3 Array{Float64,2}:
 0.666494   0.216695  0.0339015
 0.455444   0.123357  0.713102 
 0.0343181  0.506372  0.611155 

In [23]:
m1+m2

3×3 Array{Float64,2}:
 1.46257   0.901235  0.800833
 0.54766   0.875191  1.27236 
 0.778584  0.772421  1.53952 

In [24]:
transpose(m1)

3×3 Transpose{Float64,Array{Float64,2}}:
 0.796074  0.092216  0.744266
 0.684539  0.751835  0.266049
 0.766931  0.559261  0.928364

In [25]:
m1^3

3×3 Array{Float64,2}:
 2.39492  2.27153  3.26211
 1.26866  1.23576  1.80135
 2.30647  2.03523  3.00622

In [26]:
m1.^3

3×3 Array{Float64,2}:
 0.504499     0.320771   0.451096
 0.000784185  0.424979   0.174921
 0.412272     0.0188315  0.800119

In [27]:
m1.^3 == m1^3

false

In [28]:
dig = Diagonal(m1)

3×3 Diagonal{Float64,Array{Float64,1}}:
 0.796074   ⋅         ⋅      
  ⋅        0.751835   ⋅      
  ⋅         ⋅        0.928364

In [29]:
inversa1 = inv(m1)

3×3 Array{Float64,2}:
  2.16908  -1.70411   -0.765317
  1.30586   0.664508  -1.47909 
 -2.11317   1.17574    2.11459 

In [30]:
inversa2 = m1\id

3×3 Array{Float64,2}:
  2.16908  -1.70411   -0.765317
  1.30586   0.664508  -1.47909 
 -2.11317   1.17574    2.11459 

In [31]:
inversa1 == inversa2

false